### ISSUE TITLE
Vocabulary Memrise

### ISSUE THREAD

**Issue by Dishmemah** [Kokanu/Documentation#22]

**Comment by MadcapJake** [comment]
what's this one about?

**Comment by zhukant** [comment]
@MadcapJake hey there! Ideally, all discussion should happen in Discord by starting a thread and linking to the issue of concern. Unfortunately there is no way to turn off comments in GitHub, but there is a strong desire to have no discussion on GitHub, and keep all discussion in Discord, so that GitHub never contains additional insight that can't be found in Discord :) I just followed up on this on Discord, by the way:
> https://discordapp.com/channels/845822437434196048/1065255569415487540/1173160879034994728
